version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      # - run:
      #     name: Linting
      #     command: npm run lint
      - run: npm run test -- --no-watch --no-progress
      - run:
          name: Building
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                #   npm run build --prod
                echo 'build in prod'
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  npm run build --prod
              else
                  echo 'dry-branch'
              fi
        # Install AWS cli
      - run:
          name: Install aws cli
          command:
            sudo apt-get -y -qq install awscli  
      - run:
          name: Deploy to S3
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo 'deploy to master'
                #   aws --region eu-west-2 s3 sync dist s3://s3.eu-west-2.amazonaws.com/developer.api.hackney.gov.uk/ --delete
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  aws --region eu-west-2 s3 sync dist s3://s3.eu-west-2.amazonaws.com/staging.developer.api.hackney.gov.uk/ --delete
              fi
