version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.11

jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: 
          name: run tests
          command: npm run test -- --no-watch --no-progress
      - run:
          name: Building
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run build --prod --aot=true
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  npm run build --aot=true
              else
                  echo 'dry-branch'
              fi
      - run:
          name: Install aws cli
          command:
            sudo apt-get -y -qq install awscli
      # - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION      
      - run:
          name: Deploy to S3
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  aws s3 sync dist s3://developer.api.hackney.gov.uk/ --delete
              elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  aws s3 sync dist s3://staging.developer.api.hackney.gov.uk/ --delete
              fi
